resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Adds the Google Analytics tracking code to your application experience.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesComponentsGoogleAnalytics-0~
    name: Google Analytics
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords:
      - google-analytics
      - tracking
version: 1
