resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Allow Experience Users to change their passwords.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesFormsChangeUserPassword-0~
    name: Change User Password
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords:
      - experience
      - password
      - form
      - security
      - reset
version: 1
