resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Log payload data to Loggly using their HTTP API.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesLoggly-0~
    name: Loggly
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords:
      - logging
version: 1
