resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Demonstrates how to onboard LoRaWAN sensors using the Senet
      Developer Portal and Losant.
    filesPath: ./files
    globals:
      - cloudOnly: true
        description: Downlink message timeout (minutes)
        json: "65"
        key: Senet_Downlink_Timeout
      - cloudOnly: true
        description: API Key used for downlink API access (generated in the Senet
          Developer Portal)
        json: '"AK3:zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"'
        key: SENET_API_KEY
      - cloudOnly: true
        description: ""
        json: '"AK3:UUok1BiAP5YUgGpwy7cUXVrnxtG5BCfUq8hJG9zn"'
        key: SENET_DEMO_API_KEY
    id: ~exportplaceholderid-application-applicationLoRaWanWithSenetDeveloperPortal-0~
    name: LoRaWAN with Senet Developer Portal
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords: []
version: 1
