resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This node generates OAuth Tokens from Google Cloud Service Accounts.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesGcpOAuth-0~
    name: GCP OAuth
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords:
      - gcp
      - google
      - oauth
      - security
version: 1
