resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Calculates the distance, in meters, between two GPS coordinates.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesGpsDistance-0~
    name: GPS Distance
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords:
      - gps
version: 1
