resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: OEE calculations and dashboards for simulated paper machines.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-applicationOverallEquipmentEffectiveness-0~
    name: Overall Equipment Effectiveness
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords: []
version: 1
